server:
  port: 8002

spring:
  application:
    name: alibaba-dubbo-client

  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  protocol:
    name: dubbo
    port: -1

  registry:
    address: spring-cloud://localhost

  cloud:
    subscribed-services: alibaba-dubbo-server
