server:
  port: 8001

spring:
  application:
    name: alibaba-dubbo-server

  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  scan:
    base-packages: wpq.alibaba.cloud.dubbo.impl

  protocol:
    name: dubbo
    port: -1

  registry:
    address: spring-cloud://localhost
